# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/setuptools-46.4.0-python_3.8-on-linux_64, last modified Mon May 18 17:12:02 2020
# ------------------------------------------------

package:
    name: setuptools
    version: 46.4.0
source:
    patches:
        - 0001-Remove-exact-pinning-on-certifi-and-wincertstore.patch
        - 0002-disable-downloads-inside-conda-build.patch
    sha256: ea4d966bd9d0396b15ad229c568a233c0102bc7a615babd82ca9cd730c83cb57
    url: https://github.com/pypa/setuptools/archive/v46.4.0.tar.gz
build:
    entry_points:
        - easy_install = setuptools.command.easy_install:main
    number: '0'
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - python 3.8.2 hcff3b4d_14
        - readline 8.0 h7b6447c_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - certifi >=2016.9.26
        - python >=3.8,<3.9.0a0
test:
    commands:
        - easy_install --help
    imports:
        - easy_install
        - pkg_resources
        - setuptools
about:
    description: 'Setuptools is a fully-featured, actively-maintained, and stable
        library

        designed to facilitate packaging Python projects.

        '
    dev_url: https://github.com/pypa/setuptools
    doc_source_url: https://github.com/pypa/setuptools/tree/master/docs
    doc_url: http://pythonhosted.org/setuptools/
    home: https://github.com/pypa/setuptools
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Download, build, install, upgrade, and uninstall Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - nicoddemus
        - ocefpaf
