# This file created by conda-build 3.20.2
# ------------------------------------------------

package:
    name: openssl
    version: 1.1.1h
source:
    patches:
        - 0001-Don-t-use-USE_BCRYPTGENRANDOM-for-VS-older-than-2015.patch
        - gh12369.patch
    sha256: 5c9ca8774bd7b03e5784f26ae9e9e6d749c9da2438545077e6b3d755a06595d9
    url: http://www.openssl.org/source/openssl-1.1.1h.tar.gz
build:
    no_link: lib/libcrypto.so.1.1
    number: 0
    run_exports:
        - openssl >=1.1.1h,<1.1.2a
    string: h516909a_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35 h18a2f87_9
        - binutils_linux-64 2.35 heab0d09_28
        - gcc_impl_linux-64 7.5.0 hdb87b24_16
        - gcc_linux-64 7.5.0 hf34d7eb_28
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35 h769bd43_9
        - libgcc-devel_linux-64 7.5.0 h42c25f5_16
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - make 4.3 h516909a_0
        - perl 5.26.2 h516909a_1006
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
    run:
        - ca-certificates
        - libgcc-ng >=7.5.0
test:
    commands:
        - touch checksum.txt
        - openssl sha256 checksum.txt
about:
    dev_url: https://github.com/openssl/openssl
    doc_url: https://www.openssl.org/docs/man1.1.1/
    home: http://www.openssl.org/
    license: OpenSSL
    license_family: Apache
    license_file: LICENSE
    summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - carlodri
        - jakirkham
        - jjhelmus
        - msarahan
        - ocefpaf
        - pelson
