# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/tqdm-4.46.0-on-linux_canary, last modified Mon May  4 17:17:43 2020
# ------------------------------------------------

package:
    name: tqdm
    version: 4.46.0
source:
    sha256: 4733c4a10d0f2a4d098d801464bdaf5240c7dadd2a7fde4ee93b0a0efd9fb25e
    url: https://pypi.io/packages/source/t/tqdm/tqdm-4.46.0.tar.gz
build:
    entry_points:
        - tqdm = tqdm.cli:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/tqdm_1588612780200/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py36_1
        - python 3.6.10 hcf32534_1
        - readline 8.0 h7b6447c_0
        - setuptools 46.1.3 py36_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    commands:
        - tqdm --help
        - tqdm -v
    imports:
        - tqdm
about:
    dev_url: https://github.com/tqdm/tqdm
    doc_url: https://github.com/tqdm/tqdm
    home: https://pypi.python.org/pypi/tqdm
    license: MPLv2.0, MIT
    license_family: MIT
    license_file: LICENCE
    summary: A Fast, Extensible Progress Meter
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - casperdcl
        - ericdill
        - pmlandwehr
