# This file created by conda-build 3.19.4-2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/conda-package-handling-1.6.1-python_3.8-on-linux_64, last modified Wed May  6 20:35:59 2020
# ------------------------------------------------

package:
    name: conda-package-handling
    version: 1.6.1
source:
    git_ref: 1.6.1
    git_url: https://github.com/conda/conda-package-handling
build:
    entry_points:
        - cph = conda_package_handling.cli:main
    number: '0'
    script: /tmp/build/80754af9/conda-package-handling_1588797791226/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install . --no-deps -vv
    string: py38h7b6447c_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libarchive_static_for_cph 3.3.3 hf8de549_0
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - cython 0.29.17 py38he6710b0_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py38_1
        - python 3.8.2 hcff3b4d_13
        - readline 8.0 h7b6447c_0
        - setuptools 46.1.3 py38_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - python >=3.8,<3.9.0a0
        - six
        - tqdm
test:
    commands:
        - pytest tests
    imports:
        - conda_package_handling
        - conda_package_handling.archive_utils_cy
    requires:
        - mock
        - pytest
        - pytest-cov
        - pytest-mock
    source_files:
        - tests
about:
    home: https://github.com/conda/conda-package-handling
    license: BSD-3-Clause
    license_family: BSD
    license_file:
        - LICENSE
        - static_deps_licenses/bzip2.txt
        - static_deps_licenses/libarchive.txt
        - static_deps_licenses/zlib.txt
        - static_deps_licenses/zstd.txt
    summary: Create and extract conda packages of various formats
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jjhelmus
        - msarahan
